
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
      #Light Mode
      - scheme: default
        primary: light blue
        accent: blue
        toggle:
          icon: material/brightness-7
          name: Light mode
      #Dark mode
      - scheme: slate
        primary: light blue
        accent: yellow
        toggle:
          icon: material/brightness-3
          name: Dark mode
  features:
    - navigation.instant
    - navigation.tracking
    - toc.follow

site_name: Cisco NX-OS Programmability
repo_url: https://github.com/CiscoSE/NexusProgrammability
repo_name:  CiscoSE/NexusProgrammability

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
